
SCREEN_SIZE = 600
MAZE_SIZE = 10
TILE_SIZE = 240
WALL_THICKNESS = 30
PLAYER_SIZE = 70
SPEED = 2

# MAZE_SCALE = 4
# TILE_SIZE = (SCREEN_SIZE * MAZE_SCALE) // MAZE_SIZE
# WALL_THICKNESS = TILE_SIZE // 5
WALL_COLOR = "grey50"
CELL_COLOR = "goldenrod"
EXT_COLOR = "darkgreen"