
MAZE_SIZE = 10
MAZE_SCALE = 1
SCREEN_SIZE = 600
PLAYER_SIZE = 6
TILE_SIZE = (SCREEN_SIZE * MAZE_SCALE) // MAZE_SIZE
PADDING = TILE_SIZE // 10
# PADDING = 5
SPEED = 2
WALL_COLOR = "grey50"
CELL_COLOR = "goldenrod"
EXT_COLOR = "darkgreen"