
MAZE_SIZE = 20
MAZE_SCALE = 4
SCREEN_SIZE = 600
PLAYER_SIZE = 10
TILE_SIZE = (SCREEN_SIZE * MAZE_SCALE) // MAZE_SIZE
PADDING = TILE_SIZE // 10
WALL_THICKNESS = TILE_SIZE // 5
# PADDING = 5
SPEED = 4
WALL_COLOR = "grey50"
CELL_COLOR = "goldenrod"
EXT_COLOR = "darkgreen"